### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'

### ISSUE THREAD

**Issue by slain01** [Aussiemon/ljd#3]
**Hello,I tried to decompile luajit, but the following error occurred：**
Traceback (most recent call last):
  File "main.py", line 468, in <module>
    retval = main_obj.main()
  File "main.py", line 299, in main
    ast = self.decompile(self.options.file_name)
  File "main.py", line 403, in decompile
    ljd.ast.unwarper.unwarp(ast, False)
  File "C:\Users\xxx\Desktop\ljd-2021_revision\ljd\ast\unwarper.py", line 51, in unwarp
    _run_step(_fix_loops, node, repeat_until=False)
  File "C:\Users\xxx\Desktop\ljd-2021_revision\ljd\ast\unwarper.py", line 137, in _run_step
    statements.contents = step(statements.contents, **kargs)
  File "C:\Users\xxx\Desktop\ljd-2021_revision\ljd\ast\unwarper.py", line 1794, in _fix_loops
    blocks = _handle_single_loop(start, end, blocks, repeat_until)
  File "C:\Users\xxx\Desktop\ljd-2021_revision\ljd\ast\unwarper.py", line 1870, in _handle_single_loop
    loop = _unwarp_loop(start, end, body)
  File "C:\Users\xxx\Desktop\ljd-2021_revision\ljd\ast\unwarper.py", line 2070, in _unwarp_loop
    expression = expr_body + body[:i]
TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'

**Comment by Aussiemon** [comment]
If you're still interested, please upload the failing file.
