### ISSUE TITLE
luajit-2.1.0-beta3   error

### ISSUE THREAD

**Issue by weaweawe01** [Aussiemon/ljd#9]
```python main.py 1.luac
Traceback (most recent call last):
  File "main.py", line 476, in <module>
    retval = main_obj.main()
  File "main.py", line 301, in main
    ast = self.decompile(self.options.file_name)
  File "main.py", line 411, in decompile
    ljd.ast.unwarper.unwarp(ast, False)
  File "/tools/ljd/ljd/ast/unwarper.py", line 94, in unwarp
    _run_step(_unwarp_ifs, node)
  File "/tools/ljd/ljd/ast/unwarper.py", line 137, in _run_step
    statements.contents = step(statements.contents, **kargs)
  File "/tools/ljd/ljd/ast/unwarper.py", line 392, in _unwarp_ifs
    _unwarp_if_statement(start, body, end, end)
  File "/tools/ljd/ljd/ast/unwarper.py", line 1704, in _unwarp_if_statement
    else_blocks = _unwarp_ifs(else_body, else_body[-1], topmost_end)
  File "/tools/ljd/ljd/ast/unwarper.py", line 392, in _unwarp_ifs
    _unwarp_if_statement(start, body, end, end)
  File "/tools/ljd/ljd/ast/unwarper.py", line 1704, in _unwarp_if_statement
    else_blocks = _unwarp_ifs(else_body, else_body[-1], topmost_end)
  File "/tools/ljd/ljd/ast/unwarper.py", line 392, in _unwarp_ifs
    _unwarp_if_statement(start, body, end, end)
  File "/tools/ljd/ljd/ast/unwarper.py", line 1704, in _unwarp_if_statement
    else_blocks = _unwarp_ifs(else_body, else_body[-1], topmost_end)
  File "/tools/ljd/ljd/ast/unwarper.py", line 392, in _unwarp_ifs
    _unwarp_if_statement(start, body, end, end)
  File "/tools/ljd/ljd/ast/unwarper.py", line 1700, in _unwarp_if_statement
    then_blocks = _unwarp_ifs(then_body, then_body[-1], topmost_end)
  File "/tools/ljd/ljd/ast/unwarper.py", line 392, in _unwarp_ifs
    _unwarp_if_statement(start, body, end, end)
  File "/tools/ljd/ljd/ast/unwarper.py", line 1728, in _unwarp_if_statement
    then_blocks = _unwarp_ifs(body, body[-1], topmost_end)
  File "/tools/ljd/ljd/ast/unwarper.py", line 392, in _unwarp_ifs
    _unwarp_if_statement(start, body, end, end)
  File "/tools/ljd/ljd/ast/unwarper.py", line 1669, in _unwarp_if_statement
    topmost_end)
  File "/tools/ljd/ljd/ast/unwarper.py", line 1766, in _extract_if_expression
    assert false is not None
AssertionError
```

this is file zip 
[1 (2).zip](https://github.com/Aussiemon/ljd/files/11250638/1.2.zip)

issuse2 
```php
There is one more question. It's during decompilation. There will be many uv0 that cannot obtain its actual function
```
![image](https://user-images.githubusercontent.com/111571429/232497895-ffa08e3b-3296-41ff-a780-313af9859afb.png)

**Comment by weaweawe01** [comment]
I use the following warehouse. You can decrypt this file. But it's also a bunch of Vu0 that can't get its execution function

https://github.com/AzurLaneTools/ljd

**Comment by weaweawe01** [comment]
I'm trying to modify the code. But it seems to be during the ast phase. The failure to obtain the name resulted in a lot of vu0s

**Comment by weaweawe01** [comment]
I hope you can take a look
